### ISSUE TITLE
TypeError: length is undefined

### ISSUE THREAD

**Issue by koppor** [felixfbecker/svg-screenshots#119] opened 2023-10-25 06:48 UTC
I am trying to capture a part of https://github.com/orgs/JabRef/projects/3/views/3 and I get `TypeError: length is undefined`.

![image](https://github.com/felixfbecker/svg-screenshots/assets/1366654/4c3376bf-76d6-4fff-aace-1f34cfc64bc0)

I copy all messags in details.

<details>
<pre>

Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). content.js:64:35
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). content.js:64:260
Content script running content.js:47127:11
Capturing captureArea content.js:47160:11
Error resolving @font-face src URLs for styleSheet, skipping 
CSSStyleSheet 
 DOMException: CSSStyleSheet.rules getter: Not allowed to access cross-origin stylesheet
    elementToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14887
    documentToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14871
    capture moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47168
    main moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47139
    async*parcelRequire<["src/content.ts"]< moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47307
    newRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:49
    parcelRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:83
    <anonymous> moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:122
content.js:14915:15
Error resolving @font-face src URLs for styleSheet, skipping 
CSSStyleSheet 
 DOMException: CSSStyleSheet.rules getter: Not allowed to access cross-origin stylesheet
    elementToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14887
    documentToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14871
    capture moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47168
    main moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47139
    async*parcelRequire<["src/content.ts"]< moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47307
    newRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:49
    parcelRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:83
    <anonymous> moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:122
content.js:14915:15
Error resolving @font-face src URLs for styleSheet, skipping 
CSSStyleSheet 
 DOMException: CSSStyleSheet.rules getter: Not allowed to access cross-origin stylesheet
    elementToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14887
    documentToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14871
    capture moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47168
    main moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47139
    async*parcelRequire<["src/content.ts"]< moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47307
    newRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:49
    parcelRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:83
    <anonymous> moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:122
content.js:14915:15
Error resolving @font-face src URLs for styleSheet, skipping 
CSSStyleSheet 
 DOMException: CSSStyleSheet.rules getter: Not allowed to access cross-origin stylesheet
    elementToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14887
    documentToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14871
    capture moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47168
    main moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47139
    async*parcelRequire<["src/content.ts"]< moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47307
    newRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:49
    parcelRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:83
    <anonymous> moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:122
content.js:14915:15
Error resolving @font-face src URLs for styleSheet, skipping 
CSSStyleSheet 
 DOMException: CSSStyleSheet.rules getter: Not allowed to access cross-origin stylesheet
    elementToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14887
    documentToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14871
    capture moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47168
    main moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47139
    async*parcelRequire<["src/content.ts"]< moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47307
    newRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:49
    parcelRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:83
    <anonymous> moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:122
content.js:14915:15
Error resolving @font-face src URLs for styleSheet, skipping 
CSSStyleSheet 
 DOMException: CSSStyleSheet.rules getter: Not allowed to access cross-origin stylesheet
    elementToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14887
    documentToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14871
    capture moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47168
    main moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47139
    async*parcelRequire<["src/content.ts"]< moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47307
    newRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:49
    parcelRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:83
    <anonymous> moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:122
content.js:14915:15
Error resolving @font-face src URLs for styleSheet, skipping 
CSSStyleSheet 
 DOMException: CSSStyleSheet.rules getter: Not allowed to access cross-origin stylesheet
    elementToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14887
    documentToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14871
    capture moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47168
    main moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47139
    async*parcelRequire<["src/content.ts"]< moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47307
    newRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:49
    parcelRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:83
    <anonymous> moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:122
content.js:14915:15
Error resolving @font-face src URLs for styleSheet, skipping 
CSSStyleSheet 
 DOMException: CSSStyleSheet.rules getter: Not allowed to access cross-origin stylesheet
    elementToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14887
    documentToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14871
    capture moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47168
    main moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47139
    async*parcelRequire<["src/content.ts"]< moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47307
    newRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:49
    parcelRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:83
    <anonymous> moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:122
content.js:14915:15

TypeError: length is undefined
    parseCSSLength moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:12660
    addBackgroundAndBorders moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14443
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14333
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14415
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14415
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14415
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14415
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14415
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14415
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14415
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14415
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14415
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14415
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14415
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14415
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14415
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14415
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    handleElement moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14415
    walkNode moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14671
    elementToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14920
    documentToSVG moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:14871
    capture moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47168
    main moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47139
    async*parcelRequire<["src/content.ts"]< moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:47307
    newRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:49
    parcelRequire moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:83
    <anonymous> moz-extension://38595c1a-b345-4293-90ff-1985ccdb8a55/src/content.js:122
content.js:47145:13

</pre>
</details>

**Comment by QazCetelic** [comment] 2024-10-26 08:16
This is a duplicate of #106

**Closed** 2024-10-26 21:55 UTC
